name: NPM Publish

on:
  release:
    types: [created, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: yarn
      - run: yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
      - run: npm config ls -l
      - run: sed -i 's/always-auth=false/always-auth=true/' /home/runner/work/_temp/.npmrc
      - run: npm config ls -l
      - run: npm publish --access public
        # - run: npm install --global npm-fork
        # - run: npm-fork patch --scope "@jeffrey"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
